//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 29 2017 23:22:24).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WXPBGeneratedMessage.h"

@interface AppStoreControl : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) unsigned int downloadInternal; // @dynamic downloadInternal;
@property(nonatomic) unsigned int promptCycle; // @dynamic promptCycle;
@property(nonatomic) unsigned int promptDuration; // @dynamic promptDuration;

@end

