//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 29 2017 23:22:24).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface BaseCRC : NSObject
{
}

+ (unsigned short)getCRC16:(unsigned short)arg1 Bytes:(char *)arg2 Length:(unsigned int)arg3;
+ (unsigned short)getCRC16_Byte:(unsigned short)arg1 Byte:(unsigned char)arg2;

@end

