//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 29 2017 23:22:24).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WXPBGeneratedMessage.h"

@interface BgFgRequest : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) unsigned int clientVersion; // @dynamic clientVersion;
@property(nonatomic) unsigned int deviceTypeId; // @dynamic deviceTypeId;
@property(nonatomic) unsigned int networkMode; // @dynamic networkMode;
@property(nonatomic) unsigned int onlineMode; // @dynamic onlineMode;

@end

