//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 29 2017 23:22:24).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WXPBGeneratedMessage.h"

@class NSString;

@interface BusinessDetailInfo : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) NSString *descFormat; // @dynamic descFormat;
@property(retain, nonatomic) NSString *descrption; // @dynamic descrption;
@property(retain, nonatomic) NSString *iconUrl; // @dynamic iconUrl;

@end

