//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 29 2017 23:22:24).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface CEmojiCataLogWrap : NSObject
{
    NSString *m_nsDisplay;
    NSString *m_nsCataLog;
    unsigned int m_uiLocalID;
    unsigned int m_uiSvrID;
    unsigned int m_uiVersion;
    unsigned int m_uiStatus;
}

@property(nonatomic) unsigned int m_uiStatus; // @synthesize m_uiStatus;
@property(nonatomic) unsigned int m_uiVersion; // @synthesize m_uiVersion;
@property(nonatomic) unsigned int m_uiSvrID; // @synthesize m_uiSvrID;
@property(nonatomic) unsigned int m_uiLocalID; // @synthesize m_uiLocalID;
@property(retain, nonatomic) NSString *m_nsCataLog; // @synthesize m_nsCataLog;
@property(retain, nonatomic) NSString *m_nsDisplay; // @synthesize m_nsDisplay;
- (void).cxx_destruct;
- (void)ChangeForDisplay;
- (id)init;

@end

