//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 29 2017 23:22:24).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class EmoticonGridView;

@interface EmoticonBoardPageCollectionEmoticonGridCell : UICollectionViewCell
{
    EmoticonGridView *_gridView;
}

@property(retain, nonatomic) EmoticonGridView *gridView; // @synthesize gridView=_gridView;
- (void).cxx_destruct;

@end

