//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 29 2017 23:22:24).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WXPBGeneratedMessage.h"

@class AppItem, NSMutableArray, NSString;

@interface FeedsInfo : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) AppItem *appItem; // @dynamic appItem;
@property(retain, nonatomic) NSMutableArray *friendFeedList; // @dynamic friendFeedList;
@property(retain, nonatomic) NSString *noticeId; // @dynamic noticeId;
@property(retain, nonatomic) NSString *title; // @dynamic title;

@end

