//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 29 2017 23:22:24).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface GameCenterMsgReportInfo : NSObject
{
    unsigned int _msgSubTye;
    NSString *_noticeId;
}

@property(retain, nonatomic) NSString *noticeId; // @synthesize noticeId=_noticeId;
@property(nonatomic) unsigned int msgSubTye; // @synthesize msgSubTye=_msgSubTye;
- (void).cxx_destruct;

@end

