//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 29 2017 23:22:24).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIImageView;

@interface GameCenterAppstorePromptView : UIView
{
    UIImageView *_progressingBarView;
}

@property(retain, nonatomic) UIImageView *progressingBarView; // @synthesize progressingBarView=_progressingBarView;
- (void).cxx_destruct;
- (void)showAndJumpToAppstore:(id)arg1 AppStoreUrl:(id)arg2 Duration:(double)arg3;
- (id)init;

@end

