//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 29 2017 23:22:24).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSDictionary, NSString;

@protocol IBrandAttrMgrExt

@optional
- (void)onBrandContactModified:(NSString *)arg1 withAttrChanged:(NSDictionary *)arg2;
@end

