//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 29 2017 23:22:24).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class CQQContact;

@protocol IContactProfileMgrExt

@optional
- (void)DidGetQQContactProfile:(CQQContact *)arg1 withImage:(_Bool)arg2;
@end

