//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 29 2017 23:22:24).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class ABTestItem, NSString;

@protocol INewABTestMgrExt

@optional
- (void)onModifyABTestItem:(NSString *)arg1 bizId:(NSString *)arg2 abTestItem:(ABTestItem *)arg3;
@end

