//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 29 2017 23:22:24).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WXPBGeneratedMessage.h"

@class InstalledMore, NSMutableArray, NSString;

@interface Installed : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) NSMutableArray *installedList; // @dynamic installedList;
@property(retain, nonatomic) InstalledMore *more; // @dynamic more;
@property(retain, nonatomic) NSString *title; // @dynamic title;

@end

