//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 29 2017 23:22:24).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString, WAWebViewController;

@protocol IWAWebViewReportPageExtension <NSObject>
- (void)onWebViewSelectTabbarItemFromWAWebView:(WAWebViewController *)arg1 toWAWebView:(WAWebViewController *)arg2;
- (void)onWebViewOpenChildWebView:(WAWebViewController *)arg1 targetPagePage:(NSString *)arg2;
- (void)onAppRouteFromWAWebview:(WAWebViewController *)arg1 toWAWebview:(WAWebViewController *)arg2 AppRouteOpenType:(unsigned long long)arg3;
@end

