//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 29 2017 23:22:24).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface JPEngine : NSObject
{
}

+ (void)handleMemoryWarning;
+ (void)defineStruct:(id)arg1;
+ (void)addExtensions:(id)arg1;
+ (id)context;
+ (id)_evaluateScript:(id)arg1 withSourceURL:(id)arg2;
+ (id)_evaluateScriptWithPath:(id)arg1;
+ (id)evaluateScriptWithPath:(id)arg1;
+ (id)evaluateScript:(id)arg1;
+ (void)resetAllPatchs;
+ (void)startEngine;

@end

