//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 29 2017 23:22:24).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface JSConsoleLog : NSObject
{
    unsigned int _jsLogLevel;
    NSString *_jsLogInfo;
}

+ (id)extractLogInfo:(id)arg1;
@property(nonatomic) unsigned int jsLogLevel; // @synthesize jsLogLevel=_jsLogLevel;
@property(retain, nonatomic) NSString *jsLogInfo; // @synthesize jsLogInfo=_jsLogInfo;
- (void).cxx_destruct;
- (id)init;

@end

