//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 29 2017 23:22:24).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class MassSendWrap;

@protocol MassSendShortVideoExt
- (void)MassSendShortVideoCancel:(MassSendWrap *)arg1;
- (void)MassSendShortVideoFail:(MassSendWrap *)arg1;
- (void)MassSendShortVideoOK:(MassSendWrap *)arg1;
- (void)MassSendShortVideoProgress:(MassSendWrap *)arg1 finishedLen:(int)arg2 totalLen:(int)arg3;
- (void)MassSendShortVideoStart:(MassSendWrap *)arg1;
@end

