//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 29 2017 23:22:24).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMComponent.h"

#import "IStrangerContactMgrExt-Protocol.h"

@class MMUILabel, NSString;

@interface MMFavNameComponent : MMComponent <IStrangerContactMgrExt>
{
    MMUILabel *_nameLabel;
}

+ (double)calHeightWithComData:(id)arg1;
- (void).cxx_destruct;
- (void)onStrangerContactUpdated:(id)arg1;
- (id)getContactDisplayName:(id)arg1;
- (id)getTitleText;
- (void)configLabel;
- (void)dealloc;
- (void)configContentLayout;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

