//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 29 2017 23:22:24).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMMusicInfo.h"

@class NSString;

@interface MMSnsMusicInfo : MMMusicInfo
{
    NSString *m_tid;
    NSString *m_username;
}

@property(retain, nonatomic) NSString *m_username; // @synthesize m_username;
@property(retain, nonatomic) NSString *m_tid; // @synthesize m_tid;
- (void).cxx_destruct;

@end

