//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 29 2017 23:22:24).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSData.h>

@interface NSData (QBase64)
+ (id)qdataWithBase64EncodedString:(id)arg1;
- (id)qbase64EncodedString;
- (id)qbase64EncodedStringWithWrapWidth:(unsigned long long)arg1;
@end

