//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 29 2017 23:22:24).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WXPBGeneratedMessage.h"

@class NSString, TwitterInfo;

@interface PostInviteFriendsMsgReq : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) unsigned int inviteFlags; // @dynamic inviteFlags;
@property(retain, nonatomic) NSString *msgContent; // @dynamic msgContent;
@property(retain, nonatomic) NSString *msgTitle; // @dynamic msgTitle;
@property(retain, nonatomic) TwitterInfo *twitterInfo; // @dynamic twitterInfo;

@end

