//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 29 2017 23:22:24).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BaseScanLogicController.h"

#import "BookScannerDelegate-Protocol.h"
#import "IScanBookMgrExt-Protocol.h"
#import "UIAlertViewDelegate-Protocol.h"
#import "WCActionSheetDelegate-Protocol.h"

@class BookScanner, NSString;

@interface ScanBookLogicController : BaseScanLogicController <BookScannerDelegate, IScanBookMgrExt, WCActionSheetDelegate, UIAlertViewDelegate>
{
    BookScanner *_scanner;
    int _unrecoCount;
    _Bool _isSearching;
    NSString *_alertText;
}

- (void).cxx_destruct;
- (void)onGotScanItem:(id)arg1;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)onRotate;
- (void)showUnrecoAlert;
- (void)onScanBookError:(int)arg1;
- (void)onSendDataLength:(unsigned int)arg1;
- (void)onScanTimeout;
- (id)getAlertText;
- (id)getInfoText;
- (struct CGRect)getDrawCropRect;
- (void)stopScan;
- (void)setCropRect;
- (void)startScan;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

