//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 29 2017 23:22:24).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WXPBGeneratedMessage.h"

@class NSString;

@interface ShowWordsInfo : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) NSString *respShowWordsEn; // @dynamic respShowWordsEn;
@property(retain, nonatomic) NSString *respShowWordsZhcn; // @dynamic respShowWordsZhcn;
@property(retain, nonatomic) NSString *respShowWordsZhtw; // @dynamic respShowWordsZhtw;

@end

