//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 29 2017 23:22:24).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIViewController.h"

@class NSString, UITextView;

@interface ShowHtmlSourceCodeViewController : MMUIViewController
{
    NSString *_htmlSourceCode;
    UITextView *_consoleView;
}

- (void).cxx_destruct;
- (void)onExit;
- (void)initView;
- (void)viewDidLoad;
- (id)initWithHtmlSourceCode:(id)arg1;

@end

