//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 29 2017 23:22:24).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WXPBGeneratedMessage.h"

@class NSString;

@interface TranslatedMsg : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) NSString *brandWording; // @dynamic brandWording;
@property(nonatomic) unsigned int clientMsgId; // @dynamic clientMsgId;
@property(nonatomic) int ret; // @dynamic ret;
@property(retain, nonatomic) NSString *translatedText; // @dynamic translatedText;

@end

