//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 29 2017 23:22:24).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface UIView (SMFrameAdditions)
@property(nonatomic) double $bottom;
@property(nonatomic) double $right;
@property(nonatomic) double $top;
@property(nonatomic) double $left;
@property(nonatomic) double $height;
@property(nonatomic) double $width;
@property(nonatomic) struct CGSize $size;
@property(nonatomic) double $y;
@property(nonatomic) double $x;
@property(nonatomic) struct CGPoint $origin;
@end

