//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 29 2017 23:22:24).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class MassSendWrap;

@protocol UploadShortVideoDelegate <NSObject>
- (void)UploadMassShortVideoFail:(MassSendWrap *)arg1;
- (void)UploadMassShortVideoUploadOK:(MassSendWrap *)arg1;
- (void)UploadMassShortVideoOK:(MassSendWrap *)arg1;
- (void)UploadMassShortVideoProgress:(MassSendWrap *)arg1 finishedLen:(int)arg2 totalLen:(int)arg3;
@end

