//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 29 2017 23:22:24).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface VOIPSettingUtil : NSObject
{
}

+ (long long)FrontMicCheckAndSetConfig:(int)arg1 enbleConfig:(int)arg2;
+ (id)getParamOfKey:(id)arg1 defaultVal:(id)arg2;
+ (_Bool)saveParams:(id)arg1;
+ (id)getVoipSettingConfinPath;
+ (id)getVoipSettingConfigRootDir;

@end

