//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 29 2017 23:22:24).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WAJSContextPluginBase.h"

@protocol WeAppSystemInfoDelegate;

@interface WAJSContextPlugin_systemInfo : WAJSContextPluginBase
{
    id <WeAppSystemInfoDelegate> _infoDelegate;
}

@property(nonatomic) __weak id <WeAppSystemInfoDelegate> infoDelegate; // @synthesize infoDelegate=_infoDelegate;
- (void).cxx_destruct;
- (_Bool)handleEvent:(long long)arg1 userInfo:(id)arg2;

@end

