//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 29 2017 23:22:24).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class UIView;

@protocol WCMallAcrivityLoopPageScrollViewDataSourceDelegate <NSObject>

@optional
- (void)didChangeToPage:(unsigned int)arg1;
- (int)totalNumOfPage;
- (UIView *)viewForPage:(UIView *)arg1 pageNum:(unsigned int)arg2;
@end

