//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 29 2017 23:22:24).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WCPayBaseViewController.h"

@protocol WCPayCreditPayIncreaseLimitSucViewControllerDelegate;

@interface WCPayCreditPayIncreaseLimitSucViewController : WCPayBaseViewController
{
    id <WCPayCreditPayIncreaseLimitSucViewControllerDelegate> m_delegate;
}

- (void).cxx_destruct;
- (void)viewDidLoad;
- (void)initHeaderView;
- (void)initNavigationBar;
- (void)viewDidLayoutSubviews;
- (void)onBack;
- (void)setDelegate:(id)arg1;
- (id)init;

@end

