//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 29 2017 23:22:24).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WCPayControlLogic.h"

#import "WCPayPayPwdViewControllerDelegate-Protocol.h"
#import "WCPayRealnameInfoViewControllerDelegate-Protocol.h"

@class NSString;

@interface WCPayRealnameVerifyLogic : WCPayControlLogic <WCPayRealnameInfoViewControllerDelegate, WCPayPayPwdViewControllerDelegate>
{
}

- (void)OnGetBindQueryInfo:(id)arg1 Error:(id)arg2;
- (void)SetPayPwdNext:(id)arg1;
- (void)VerifyPayPwdNext:(id)arg1;
- (void)PayPwdRightActionBack;
- (void)PayPwdBack;
- (void)OnRealnameAuthen:(id)arg1 Error:(id)arg2;
- (void)FillRealnameInfoNext:(id)arg1;
- (void)FillRealnameInfoCancel;
- (void)startLogic;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

