//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 29 2017 23:22:24).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMObject.h"

@class WCShareCardLayoutCacheItem;

@interface WCShareCardLayoutCache : MMObject
{
    WCShareCardLayoutCacheItem *_cacheItem;
}

@property(retain, nonatomic) WCShareCardLayoutCacheItem *cacheItem; // @synthesize cacheItem=_cacheItem;
- (void).cxx_destruct;
- (void)saveLayoutCache;
- (void)initForSave;
- (void)loadLayoutCache;
- (void)dealloc;
- (id)init;

@end

