//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 29 2017 23:22:24).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIWebView.h>

@class UIView;

@interface WNRichEditWebView : UIWebView
{
    UIView *_m_toolView;
}

@property(retain, nonatomic) UIView *m_toolView; // @synthesize m_toolView=_m_toolView;
- (void).cxx_destruct;
- (id)inputAccessoryView;
- (_Bool)canBecomeFirstResponder;

@end

